name: Parcial 2
on: push
env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      - name: Configurar python 3.12
        uses: actions/setup-python@v5
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Ejecutar tests
        run: pytest tests/ -v --tb=short --junitxml=report.xml
      - name: Subir reporte
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.xml
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      - name: Configurar Docker QEMU
        uses: docker/setup-qemu-action@v3
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login en Docker Hub
        uses: docker/login-actions@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extraer metadatos
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Subir imagen a Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          
        
        
